# Generated by Django 3.2.6 on 2021-08-19 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PledgeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='pledge', to='pledge.pledge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
