# Generated by Django 3.2.6 on 2021-09-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_description'),
        ('posts', '0003_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='activities.activity'),
        ),
    ]
