# Generated by Django 3.2.6 on 2021-09-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_symbol'),
        ('posts', '0004_post_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='teams.team'),
        ),
    ]
