# Generated by Django 3.2.6 on 2021-10-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_rename_backgroundcolor_challenge_background_color'),
        ('posts', '0005_post_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='challenges.challenge'),
        ),
    ]
