# Generated by Django 3.2.6 on 2021-11-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_challenge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
    ]
