# Generated by Django 3.2.6 on 2021-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210816_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='symbol',
            field=models.CharField(default='ok', max_length=20),
            preserve_default=False,
        ),
    ]
