# Generated by Django 3.2.6 on 2021-11-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211004_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accessories_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='clothe_color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='clothe_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='eyebrow_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='facial_hair_color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='facial_hair_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='graphic_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hair_color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='mouth_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='skin_color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='style',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='top_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
