# Generated by Django 3.2.6 on 2021-11-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211101_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eye_type',
            field=models.IntegerField(default=0),
        ),
    ]
