# Generated by Django 3.2.6 on 2021-11-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_eye_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='accessories_type',
            new_name='accessoriesType',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='clothe_color',
            new_name='clotheColor',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='clothe_type',
            new_name='clotheType',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='eye_type',
            new_name='eyeType',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='eyebrow_type',
            new_name='eyebrowType',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='facial_hair_color',
            new_name='facialHairColor',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='facial_hair_type',
            new_name='facialHairType',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='graphic_type',
            new_name='graphicType',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='hair_color',
            new_name='hairColor',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='mouth_type',
            new_name='mouthType',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skin_color',
            new_name='skinColor',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='top_type',
            new_name='topType',
        ),
    ]
