# Generated by Django 3.2.6 on 2021-09-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='isSourceTransport',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
