# Generated by Django 3.2.6 on 2021-09-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_emission_issourcetransport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emission',
            name='date',
        ),
    ]
