# Generated by Django 3.2.6 on 2021-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_remove_emission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='emission',
            name='weekNo',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='emission',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
