# Generated by Django 3.2.6 on 2021-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
