# Generated by Django 3.2.6 on 2021-10-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20211007_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='backgroundColor',
            new_name='background_color',
        ),
    ]
