# Generated by Django 3.2.6 on 2021-10-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_rename_backgroundcolor_challenge_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='goal',
            field=models.IntegerField(default=0),
        ),
    ]
