# Generated by Django 3.2.6 on 2021-11-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_auto_20211104_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_team_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
