# Generated by Django 3.2.6 on 2021-11-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_symbol'),
        ('challenges', '0008_challenge_is_team_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(auto_created=True, default=0)),
                ('score', models.IntegerField(auto_created=True, default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_challenge_team', to='challenges.challenge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_team', to='teams.team')),
            ],
        ),
    ]
