# Generated by Django 3.2.6 on 2021-11-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_challengeteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='team_challenge_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
    ]
