# Generated by Django 3.2.6 on 2021-11-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='ok', max_length=200),
            preserve_default=False,
        ),
    ]
